<?php
// Automatically Generated by TestLink Installer - Thu, 04 Sep 25 00:29:22 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'pwd_root');
define('DB_HOST', '192.168.31.232');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
